env: "MARL_env_fake_cov_small"

env_args:
  "key": null
  "graph_file_json": "./storage_graph/TEST_adjusted"
  "trace_path": "./storage_inference/1223_1153___REPORT___1500s_2500t_4c___REPORT_adjusted__lonle_d1lonle_d2__.nc"
  "rewards_args":
    "thresholds": [1.,2.5]    # Different than MARL_env
    "cost_threshold": 750
    "n": 2.5
    "fixed_cost_tamping": 0.017
    "variable_cost_tamping": 0.030
    "rate_of_decay_tamping": 0.55
    "fixed_cost_renewal": 1
    "variable_cost_renewal": 3.1
    "rate_of_decay_renewal": 0.45
  "max_timesteps": 200
  "n_actions": 4
  "n_obs": 2
  "trace_mean": True
  "node_length": 150
  "sum_rewards": False
  "seed": None